export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
  }
  
  export default function RootLayout({
    children,
  }: {
    children: React.ReactNode
  }) {
    return (
   
    <>
      {children}
      <h4> All product details layout... </h4>
    </>
 
    )
  }